version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: sfx_arena_backend_web
    command: /start
    volumes:
      - .:/app
      - ./static:/app/static
    ports:
      - 8010:8010
    env_file:
      - ./env/.local
    depends_on:
      - db

  db:
    image: postgis/postgis:14-3.2  # Production Dockerfile should also be updated
    volumes:
      - sfx_data:/var/lib/postgresql/data/
    env_file:
      - ./env/.local

volumes:
  sfx_data: