version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: sfx-trening_web_prod
    command: /start
    volumes:
      - /var/www/sfx/static/:/app/static
      - /var/www/sfx/media/:/app/media
    ports:
      - 8010:8000
    env_file:
      - ./env/.production
    depends_on:
      - db
  db:
    image: postgis/postgis:15-3.3
    volumes:
      - sfx_data_production:/var/lib/postgresql/data/
    env_file:
      - ./env/.production


volumes:
  sfx_data_production:

