# Generated by Django 4.2.15 on 2024-09-29 04:56

from django.db import migrations, models
import tasks.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_studenttask_options_alter_task_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(default=1, upload_to='task_images/', validators=[tasks.validators.validate_image], verbose_name='Image'),
            preserve_default=False,
        ),
    ]
